---
apiVersion: v1
kind: ConfigMap
metadata:
  name: infisical-0.132.1-defaults
  namespace: ${releaseNamespace}
data:
  values.yaml: |
    infisical:
      image:
        repository: infisical/infisical
        tag: "v0.132.1-postgres"
        pullPolicy: IfNotPresent
