---
apiVersion: v1
kind: ConfigMap
metadata:
  name: victoria-metrics-0.20.0-defaults
  namespace: ${releaseNamespace}
data:
  values.yaml: |
    server:
      retentionPeriod: 12
      service:
        type: LoadBalancer
      persistentVolume:
        enabled: true
        size: 100Gi
      serviceMonitor:
        enabled: true
        extraLabels:
          prometheus.kommander.d2iq.io/select: "true"
      scrape:
        enabled: true
