---
apiVersion: v1
kind: ConfigMap
metadata:
  name: victoria-logs-0.11.1-defaults
  namespace: ${releaseNamespace}
data:
  values.yaml: |
    server:
      retentionPeriod: 12
      extraArgs:
        envflag.enable: true
        envflag.prefix: VM_
        loggerFormat: json
        httpListenAddr: :9428
        syslog.listenAddr.tcp: :514
        syslog.listenAddr.udp: :514
      mode: deployment
      service:
        type: LoadBalancer
      persistentVolume:
        enabled: true
        size: 500Gi
      serviceMonitor:
        enabled: true
        extraLabels:
          prometheus.kommander.d2iq.io/select: "true"
    dashboards:
      enabled: true
      labels:
        grafana_dashboard: "1"
      namespace: ${releaseNamespace}
