apiVersion: v1
kind: Namespace
metadata:
  name: n8n
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: n8n
  namespace: n8n
spec:
  serviceName: "n8n-service"
  replicas: 1
  selector:
    matchLabels:
      app: n8n
  template:
    metadata:
      labels:
        app: n8n
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - name: n8n
          image: n8nio/n8n:1.77.3
          ports:
            - containerPort: 5678
              name: http
          env:
            - name: OLLAMA_HOST
              value: "ollama:11434"
          volumeMounts:
            - name: storage
              mountPath: /home/node/.n8n
  volumeClaimTemplates:
    - metadata:
        name: storage
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 40Gi
---
apiVersion: v1
kind: Service
metadata:
  name: n8n
  namespace: n8n
spec:
  type: LoadBalancer
  selector:
    app: n8n
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5678
