---
apiVersion: v1
kind: ConfigMap
metadata:
  name: victoria-logs-0.9.4-defaults
  namespace: ${releaseNamespace}
data:
  values.yaml: |
    server:
      mode: deployment
      service:
        type: LoadBalancer
      persistentVolume:
        enabled: true
        size: 50Gi
      serviceMonitor:
        enabled: true
        extraLabels:
          prometheus.kommander.d2iq.io/select: "true"
    dashboards:
      enabled: true
      labels:
        grafana_dashboard: "1"
      namespace: ${releaseNamespace}
