---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: victoria-metrics
  namespace: ${releaseNamespace}
spec:
  interval: 10m
  timeout: 1m
  url: https://victoriametrics.github.io/helm-charts/
