---
apiVersion: v1
kind: ConfigMap
metadata:
  name: services-0.116.0-defaults
  namespace: ${releaseNamespace}
data:
  values.yaml: |
    infisical:
      image:
        repository: infisical/infisical
        tag: "v0.116.0-postgres"
        pullPolicy: IfNotPresent
